"""second

Revision ID: c1bd951adbef
Revises: 2c3e4b8615ed
Create Date: 2016-12-11 16:10:13.735534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bd951adbef'
down_revision = '2c3e4b8615ed'
branch_labels = None
depends_on = None


def upgrade():
    # commands changed by me
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('sex')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
